#!/usr/bin/env bash
# PostToolUse hook: BLOCK if PHP file lacks declare(strict_types=1).
# Skip blade templates, vendor, third-party.

set -euo pipefail

input=$(cat)
file=$(echo "$input" | jq -r '.tool_input.file_path // .tool_response.filePath // empty')

[ -z "$file" ] && exit 0

case "$file" in
    *.blade.php) exit 0 ;;
    */vendor/*) exit 0 ;;
    */node_modules/*) exit 0 ;;
    *.php) ;;
    *) exit 0 ;;
esac

[ -f "$file" ] || exit 0

# Skip migration / config files generated by Laravel that often omit strict types
case "$file" in
    */config/*.php) exit 0 ;;
    */bootstrap/*.php) exit 0 ;;
    */public/*.php) exit 0 ;;
    */routes/console.php) exit 0 ;;
esac

# Look in the first 10 lines for declare(strict_types=1)
head -n 10 "$file" | grep -qE 'declare\(\s*strict_types\s*=\s*1\s*\)' && exit 0

{
    echo "❌ $file is missing declare(strict_types=1);"
    echo "Add as the first statement after <?php:"
    echo ""
    echo "    <?php"
    echo ""
    echo "    declare(strict_types=1);"
    echo ""
} >&2
exit 2
